# Generated by Django 3.1.5 on 2021-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=300, null=True, verbose_name='List Name')),
                ('finish_yet', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ' To Do List ',
            },
        ),
    ]
