# Generated by Django 3.1.5 on 2021-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210408_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
