# Generated by Django 3.1.5 on 2021-04-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0003_todouser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='todo_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
