# Generated by Django 3.1.5 on 2021-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20210410_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
