# Generated by Django 3.1.5 on 2021-04-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_auto_20210410_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
